
<section class="access section fcl">
<h2 class="din_bold"><img class="js-imgchange" src="./img/s.gif" data-src="./img/ttl_access.svg" alt="ACCESS"></h2>
<div class="body">

<p>
〒107-0052　東京都港区赤坂8-5-32 <br class="onlySp">TanakaKoma Bldg. 6F<br>
T.03-6434-7217 / F.03-6434-7218
</p>

<p>
青山一丁目駅<br>
東京メトロ半蔵門線・銀座線、都営地下鉄大江戸線「出口4南」より徒歩3分
</p>

</div><!-- /body -->
</section><!-- /section -->

<div class="map js-anim"><div class="googlemap"></div></div>
